
syntax = "proto3";

service SceneStreamService {
	rpc GetSceneList(Empty) returns (SceneListReply);
	rpc AskSceneInfo(SceneReq) returns (SceneInfoReply);
	rpc GetSceneObjectData(SceneReq) returns (stream SceneObjectsReply);
}

message Empty{}

message Vec2 {
	float x = 1; float y = 2;
}

message Vec3 {
	float x = 1; float y = 2; float z = 3;
}

message Quaternion {
	float w = 1; float x = 2; float y = 3; float z = 4;
}

message Vertex {
	Vec3 position = 1; Vec3 normal = 2; Vec2 uv = 3;
}

message ObjectReply {
	Vec3 position = 1;
	Quaternion rotation = 2;
	Vec3 scale = 3;

	repeated Vertex vertices = 4;
}

message SceneListReply {
	repeated string sceneNames = 1;
}

message SceneReq {
	string name = 1;
}

message SceneInfoReply {
	bool status = 1;							
	int32 totalObjects = 2;				
}

message SceneObjectsReply {					
	repeated ObjectReply objects = 1;			
}