
syntax = "proto3";

service SceneStreamService {
	rpc GetSceneList(Empty) returns (SceneListReply);
	rpc AskSceneInfo(SceneReq) returns (SceneInfoReply);
	rpc GetSceneObjectData(SceneReq) returns (stream ObjectReply);
}

message Empty{}

message Vec2Reply {
	float x = 1; float y = 2;
}

message Vec3Reply {
	float x = 1; float y = 2; float z = 3;
}

message QuaternionReply {
	float w = 1; float x = 2; float y = 3; float z = 4;
}

message VertexReply {
	Vec3Reply position = 1; 
	Vec3Reply normal = 2; 
	Vec2Reply uv = 3;
}

message ObjectReply {
	Vec3Reply position = 1;
	QuaternionReply rotation = 2;
	Vec3Reply scale = 3;

	repeated VertexReply vertices = 4;
}

message SceneListReply {
	repeated string sceneNames = 1;
}

message SceneReq {
	string name = 1;
}

message SceneInfoReply {
	bool status = 1;							
	int32 totalObjects = 2;				
}